<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>arrowLeft_ActionALL</name>
   <tag></tag>
   <elementGuidId>e98fd893-e0db-4875-ad69-cc6fdcca9dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='actionInput']/ancestor::div[@aria-describedby='react-flow__node-desc-1']/descendant::div[@data-handlepos='left']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
