<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_ProvidenceHospital</name>
   <tag></tag>
   <elementGuidId>5efb89b4-f2dc-49fd-8581-29e9de8ed784</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[text()='Enterprise-Applications']/ancestor::a/following-sibling::div/descendant::p[contains(text(),'Providence-Hospital')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
