<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_WarningCondition</name>
   <tag></tag>
   <elementGuidId>2ea901e5-0400-4a08-903e-1801bfe3127f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'tabpanel-2')]/descendant::button[contains(@id,'accordion-button')]/descendant::div[last()-1]/descendant::p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
