<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>arrowLeft_ExistingMedication</name>
   <tag></tag>
   <elementGuidId>a915529d-3ab3-4094-8dd4-d19c6f4b1e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-id='subject']/preceding-sibling::div[@data-id='entityType-5']/descendant::div[@data-handlepos='left']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
