<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NewApplication</name>
   <tag></tag>
   <elementGuidId>54763484-9056-486b-9fec-ae1e20dc99a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-1v0vp0i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;New Application&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9043643-945e-4f05-890a-1934b90ad1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1383adf-7103-4435-8c58-b817223b4e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1v0vp0i</value>
      <webElementGuid>9c7ddc96-922f-4ba2-b20f-389fb8693bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Application</value>
      <webElementGuid>9d163a07-2189-44dc-8801-e919dc3e33e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-d4res&quot;]/div[@class=&quot;css-u0mlfu&quot;]/div[@class=&quot;css-g07lqp&quot;]/div[@class=&quot;css-1yyva0c&quot;]/div[@class=&quot;css-wtnpe1&quot;]/div[@class=&quot;css-1a1nvtv&quot;]/div[@class=&quot;css-1brslgc&quot;]/div[@class=&quot;css-nznorp&quot;]/div[@class=&quot;css-1mucns2&quot;]/div[@class=&quot;css-70qvj9&quot;]/button[@class=&quot;chakra-button css-1v0vp0i&quot;]</value>
      <webElementGuid>781600fe-309d-4b32-a46b-e9d7b5a5464c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
